from models.user import User
from models.client_profile import ClientProfile
from models.professional import Professional
from models.visual_preference import VisualPreference
from models.facial_analysis import FacialAnalysis
from models.recommendation import Recommendation
from models.simulation import Simulation
from models.appointment import Appointment
from models.hair_history import HairHistory
